import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          List of <a href="https://nextjs.org">Components</a>
        </h1>
        <ul>
          <li>Name</li>
          <li>Pict</li>
          <li>Contact</li>
          <li>Language</li>
          <li>Skills</li>
          
        </ul>


        <div class="document skn-mls2 fontsize fontface vmargins hmargins pagesize">

        </div>
      </main>
    </div>
  )
}
